(add-to-list 'sml/replacer-regexp-list '("^~/Work/api" ":API:") t)
(add-to-list 'sml/replacer-regexp-list '("^~/Work/goprovision/" ":GP:") t)
(add-to-list 'sml/replacer-regexp-list '("^~/Work/zenbuild/" ":ZENIX:") t)
(add-to-list 'sml/replacer-regexp-list '("^~/Work/zedcloud/" ":CLOUD:") t)
(add-to-list 'sml/replacer-regexp-list '("^~/Work/samples/" ":SAMPLES:") t)
(add-to-list 'sml/replacer-regexp-list '("^~/Work/zcli/" ":ZCLI:") t)
(add-to-list 'sml/replacer-regexp-list '("^~/Work/cluster-configs/" ":CC:") t)
(add-to-list 'sml/replacer-regexp-list '("^~/Work/config-builder/" ":CB:") t)
(add-to-list 'sml/replacer-regexp-list '("^~/Work/sre-containers/" ":SC:") t)
(add-to-list 'sml/replacer-regexp-list '("^~/Work/eve/" ":EVE:") t)

(provide 'my-sandboxes)
